pipeline:
  packwizInstall:
    image: bazsalanszky/packwiz-installer
    commands:
      - java -jar /packwiz-installer-bootstrap.jar -g "file://$PWD/pack.toml" || echo "Done"
  packStuff:
    image: alpine
    commands:
      - apk update
      - apk add zip
      - zip -r zsazs.zip mods CustomSkinLoader
      - cd mods && zip mods.zip *.jar
  release:
    image: plugins/gitea-release
    settings:
      api_key: 
        from_secret: gitea_token
      base_url: https://git.toldi.eu
      files:
      - zsazs.zip
      - mods/mods.zip
      checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag 
