name: Pack

on: push


jobs:
  packwizInstall:
    runs-on: ubuntu-latest
    container:
      image: bazsalanszky/packwiz-installer
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run packwiz installer
        run: java -jar /packwiz-installer-bootstrap.jar -g "file://$PWD/pack.toml" || echo "Done"
